### ISSUE TITLE
Screenshot missing on package site

### ISSUE THREAD

**Issue by ArneTR** [green-kernel/powerletrics#11]
https://pypi.org/project/powerletrics/
<img width="262" alt="Screenshot 2024-11-13 at 2 43 55 PM" src="https://github.com/user-attachments/assets/7506c5b9-d700-4a47-a263-a37659fd1139">

**Comment by ribalba** [comment]
Fixed here: https://github.com/green-kernel/powerletrics/commit/fc28ee7145817fc1d80892d114a5c28bb15aa4dd
